{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agent-hub.fullname" . }}
  labels:
    {{- include "agent-hub.labels" . | nindent 4 }}
    cloud.sealos.io/app-deploy-manager-domain: {{ include "agent-hub.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.largeClientHeaderBuffers.enabled }}
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size {{ .Values.ingress.largeClientHeaderBuffers.clientHeaderBufferSize }};
      large_client_header_buffers {{ .Values.ingress.largeClientHeaderBuffers.count }} {{ .Values.ingress.largeClientHeaderBuffers.size }};
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "agent-hub.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tlsSecretName | quote }}
{{- end }}
